sudo: false
language: python
python:
  - 3.6
before_script:
  - aws configure set default.region ap-northeast-1
  # - aws configure set aws_access_key_id 'YOUR_ACCESS_KEY'
  # - aws configure set aws_secret_access_key 'YOUR_SECRET_KEY'
script:
  - invoke shunit
  - invoke unittest
