sudo: false
language: bash
before_script:
  - pip install -r requirements.txt
  - aws configure set default.region ap-northeast-1
  - aws configure set aws_access_key_id ''
  - aws configure set aws_secret_access_key ''
script:
  - invoke shunit
  - invoke unittest
